import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import RedirectLayout from "@/firebase/RedirectLayout";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";

const fontSans = FontSans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased container",
          fontSans.variable
        )}
      >
        <Header />
        <RedirectLayout>{children}</RedirectLayout>
      </body>
    </html>
  );
}
