import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RedirectLayout from "@/firebase/redirectLayout";
import LogoutButton from "@/components/LogoutButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RedirectLayout>
          <LogoutButton />
          {children}
        </RedirectLayout>
      </body>
    </html>
  );
}
